name: CI-disabled

on:
  workflow_dispatch:
    inputs:
      note:
        description: "CI désactivée temporairement pour focus MVP"
        required: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: echo "CI désactivée temporairement (focus MVP)."
